cours = 'pyThon pour les Nuls'
print(cours.upper())
print(cours.capitalize())
print(cours.lower())
print(cours.find('y'))
print(cours.find('Y'))
print(cours.replace('Thon', 'thon'))
print('python' in cours)
cours = cours.replace('Thon', 'thon')
print(cours)
print('python' in cours)
print(cours[0:3])
print("012")
print("imprime les éléments de la chaine de caractère de 0 à 3 EXCLUS")